### ISSUE TITLE
Is 2.7.x branch up to date with CMFPlone 5.1?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mockup#1006]
Since the 2.7.8 release in May 2019, there was only one change on the 2.7.x branch for 5.1: PR #930, backporting lost TinyMCE translations.
Can someone take care of getting that change into the `Products.CMFPlone` 5.1.x branch, or confirm that this has already been done?

Is mockup ready for release then, or is someone aware of stuff we desperately need to fix (or backport) ?
(I can do the release, or someone else.)

**Comment by vincentfretin** [comment]
I backported some of my fixes from master https://github.com/plone/mockup/pull/1007

**Comment by vincentfretin** [comment]
and https://github.com/plone/Products.CMFPlone/pull/3159 because the toolbar pattern was in Products.CMFPlone in Plone 5.1.x (please someone review it so I can merge)

**Comment by vincentfretin** [comment]
After this we need to rebuild the bundles and add an upgrade step in Products.CMFPlone.

**Comment by vincentfretin** [comment]
https://github.com/plone/Products.CMFPlone/pull/3161 and https://github.com/plone/plone.app.upgrade/pull/236
