### ISSUE TITLE
Release for 5.2.3

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mockup#1026]
Can we get a new release for Plone 5.2.3? I'd like to try and get that out this week, without possibly breaking changes.
@thet [bumped the version to 4.0.0](https://github.com/plone/mockup/commit/292c6e352190c181416f53a155aa51c8b143a79d) three days ago. That means we should have a 3.x branch.
What would be a good branching point? I guess either commit 590d229599433bac4f2265ce7dfa7857c408bf17 with the changes of #924, or commit cf6e6151eb28dd05dfaf1267799238aa0a93e6b5 from early September.

@thet, could you do that, or advise otherwise? So: maintenance branches for mockup and plone.staticresources, let coredev 5.2 use them, sync the mockup branch with plone.staticresources, and make releases. I can do some of this as well.

**Comment by fredvd** [comment]
@thet  And are there recent commits we can/should cherry-pick to a 3.x maintenance branch?  For example these pat-select fixes from @MrTango ?  https://github.com/plone/mockup/commit/0bb97a41c2c518d855d6edba223a48969192857f

**Comment by thet** [comment]
I've cut a 3.x branch:
https://github.com/plone/mockup/tree/3.x

TODO:
- Update plone.staticresources

**Comment by mauritsvanrees** [comment]
I have released `mockup` 3.2.3 and accompanying `plone.staticresources` 1.4.0.
