### ISSUE TITLE
[ES6] Theming ControlPanel, can we include bootstrap here?

### ISSUE THREAD

**Issue by MrTango** [plone/mockup#1085]
The styling and modals in Theming CP are off right nwo, reason is that we don't have bootstrap and barcelonete there, because Diazo is off there. But i don't see any reason why we couln't include css from barcelonete including bootstrap there, too make it nice. Diazo can still be off there, which makes sense. @agitator @jensens @thet what do you think?

**Comment by jensens** [comment]
- bare bootstrap makes sense
- barceloneta might not be there IIRC

**Comment by MrTango** [comment]
barceloneta is always there in ClassicUI

**Comment by MrTango** [comment]
I added it liek this for now:
    <link
        rel="stylesheet"
        type="text/css"
        tal:attributes="href string:${context/portal_url}/++theme++barceloneta/css/barceloneta.min.css"
        />
in https://github.com/plone/plone.app.theming/pull/205
