### ISSUE TITLE
[ES6] @@theming-controlpanel-mapper broken, need theming mapper pattern

### ISSUE THREAD

**Issue by MrTango** [plone/mockup#1086]
Should we give the theming editor up?
Uploading a theme will still work, but you can edit anymore, which would be limited anyway without SCSS compiling.
But things like uploading TinyMCE templates into your theme TTW will not be possible either.
There is still portal_skins/custom which could be used for this kind of quick and dirty things.
@thet @jensens @agitator @yurj ?

**Comment by jensens** [comment]
I would keep  this feature. I think we agreed, over the long run `portal_skins` should be deprecated.

**Comment by MrTango** [comment]
portal_skins should go nowhere, accept someone builds an alternative for that, we don't have one yet.
Plone core is not using it, but leave the functionality for addons if you don't have an alternative for it.
If you want to keep the theming editor, than you have to find someone to port the themingmapper pattern and the filemanager pattern. I'm not willing to work on that in my spare time.

**Comment by jensens** [comment]
Indeed, its a community effort.

**Comment by MrTango** [comment]
see also discussion and poll here: https://community.plone.org/t/giving-up-ttw-theming-in-plone-6-classic-ui/14474

**Comment by MrTango** [comment]
wont fix
