### ISSUE TITLE
accessible focus handling for overlays

### ISSUE THREAD

**Issue by RMattB** [plone/mockup#11]
- add anchor element around title of all overlays
- add anchor element around buttons/links which activate all overlays
- when overlay without a form is activated, set focus to the overlay title anchor 
- when overlay close link or overlay form cancel button are clicked, set focus to the originating button's anchor
- when close link loses focus, set focus to the overlay title anchor

**Comment by nzambello** [comment]
I'd like to work on this, I'm planning to open a PR shortly.
