### ISSUE TITLE
[ES6] querystring pattern  Location criterion depth handling broken

### ISSUE THREAD

**Issue by fredvd** [plone/mockup#1108]
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/robot/test_querystring.robot

While trying to fix failing robotframework tests for Plone 6 it turns out the broken test does signal broken functionality. There are also (still open) way older issues about the location criterion for Plone 5.X like #578 and  #678. 

An extra complication is that the test Scenario's Add a new collection item,  add criteria and then test the number of results in the Preview window, but the Test doesn't save the collection Item first.  For some added criterions like Location the preview results have been known to be wrong or different until the collection has been saved first. 

The robot tests for the Location creates in the Setup Layer a folder structure /a/b/c/ ,  2 documents and alink and then adds a new collection in /a/ . But the first Scenario "Location query Current"  already fails on the number of results returned. 

Initally after adding the Location Criterion is in 'Custom' mode. The first test sets it to Current (./) . When you manually test this:

* In Plone 5.2 the when you select 'Current' for the Location criterion, the depth drop down from Custom is removed and the request with the querystring contains depth 1 for a relative path "."  ->  (.::1) 
> http://localhost:8080/plone/nl/test2/@@querybuilder_html_results?query.i:records=path&query.o:records=plone.app.querystring.operation.string.relativePath&query.v:records=.::1&sort_on=

* In Plone 6.0 mockup es6 branch, when you switch from Custom to Current (./), the depth drop down from Custom is not removed.  And the query sent to the backend:

> http://localhost:8081/Plone/coltest/@@querybuilder_html_results?query.i:records=path&query.o:records=plone.app.querystring.operation.string.relativePath&query.v:records=.::1::-1&sort_on= 

Here is the trigger for the test failure also visible: the depth drop down adds an extra `::-1` unlimited to the already filled in .::1 query .  Because of this the first test breaks, in Plone 5.2 only 1 other item is found in the current folder, the querystring for Plone 6 finds all items in the subtree. 

<img width="960" alt="depth select not removed" src="https://user-images.githubusercontent.com/394784/149578405-a153bca3-0fce-4d12-b0ea-587c53bd99d1.png">

And for each switch you make between Location Custom and Current, an extra 'depth' drop down is added to the querystring widget: 

<img width="960" alt="Screenshot 2022-01-14 at 21 08 09" src="https://user-images.githubusercontent.com/394784/149578537-907f4b37-f27b-4d7f-bfe1-47430ef5f84d.png">

Subsequent tests break for similar reasons with other number of items found

**Comment by MrTango** [comment]
@fredvd Could you please check, if this is still open.
Should be fixed

**Comment by fredvd** [comment]
Checked the location, works again,  indeed!  Thanks @petschki
