### ISSUE TITLE
overview of failing/missing/skipped tests

### ISSUE THREAD

**Issue by iham** [plone/mockup#1122]
Test overview

Core:
 - [x] i18n
 - [x] utils

Patterns:
 - [x] autotoc
 - [x] backdrop
 - [x] contentloader
 - [x] cookietrigger
 - [x] formautofocus
 - [x] livesearch (thet)
 - [x] markspeciallinks (petschki)
 - [x] modal (petschki)
 - [x] passwordstrength
 - [x] preventdoublesubmit
 - [x] querystring
 - [x] relateditems (frapell)
 - [x] search
 - [x] select2
 - [x] sortable
 - [x] structure (thet)
 - [x] textareamimetimeselector (petschki #1231)
 - [x] tinymce
 - [x] toggle
 - [x] toolbar
 - [x] tree 
 - [x] upload
 
###  no matching tests:

- [ ] recurrence
- [ ] controlpanels
- [ ] datatables
- [ ] manageportlets
- [ ] navigationmarker
- [ ] structure-updater
- [ ] texteditor

  
### skipped tests:
 - [ ] formunloadalert

**Comment by mauritsvanrees** [comment]
Does something still need to happen here?

**Comment by iham** [comment]
This is just a collection of js tests that failed, where skipped and so on. **If** those tests are fixed, ported, removed, ... this can be closed.
