### ISSUE TITLE
How to update translations?

### ISSUE THREAD

**Issue by wesleybl** [plone/mockup#1147]
Some terms that the `mockup` uses are not translated into Portuguese. For example:

https://github.com/collective/plone.app.locales/blob/5.1.x/plone/app/locales/locales/pt_BR/LC_MESSAGES/widgets.po#L420

I added the translation directly to the `plone.app.locales` used by my instance, but the translation was not done on the screen.

I also tried compiling the `plone-editor-tools` bundle, but that didn't help either. How do I update the translation?

I'm using:

Plone 5.2.7
mockup 3.2.7

**Comment by yurj** [comment]
Maybe https://github.com/plone/mockup/issues/488#issuecomment-647618395 ?

**Comment by wesleybl** [comment]
hum then the translations are stored in local storage. I have to clear the local storage to see new translations.

This is documented in:

https://github.com/plone/mockup/tree/3.x#install--run-tests

Thanks @yurj for showing this.

And thanks @vincentfretin for documenting this.

@thet you removed this documentation in https://github.com/plone/mockup/commit/68d447225a13ab42f1e688476a2ddd8491d59612#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L79.

I think this is important information and should be in the README. In the new version of the mockup, do the translations work differently?

**Comment by wesleybl** [comment]
@erral can you help here?

**Comment by erral** [comment]
We are currently missing the i18n message extraction script. Until that is ready we can't stablish a working workflow for this. Let's handle this script first, and then we will resync all PO files.

**Comment by thet** [comment]
Fixed by: https://github.com/plone/mockup/pull/1190
