### ISSUE TITLE
tinymce changes in menubar setting when upgrading from 6.0.0a[1,2,3] to a4

### ISSUE THREAD

**Issue by yurj** [plone/mockup#1158]
in Plone6.0.0a[1,2,3] the menu setting is:
```
edit
table
format
toolsview
insert
```

in Plone6.0.0a4 it is:
```
edit
table
format
tools
view
insert
```
If we upgrade from 6.0.0a]1,2,3] to a4 this settings remains unchanged, thus the "View" bar is not displayed. If I create a new site, I can see this setting being correct.

**Comment by petschki** [comment]
Can we close this?

**Comment by yurj** [comment]
I think it was a problem in the upgrade step. We can close it, was alpha.
