### ISSUE TITLE
pat-modal: form AJAX call cannot handle file upload

### ISSUE THREAD

**Issue by akonstanczak** [plone/mockup#1166]
handleFormAction method in this pattern calls $form.serializeArray() method which excludes files from being serialized, see: https://api.jquery.com/serializearray/ This issue is blocking any AJAX file/image upload using modals.

**Comment by petschki** [comment]
reading the code, a very quick workaround for this would be to set `disableAjaxFormSubmit: true` in `actionOptions`: 

```
<a href="${python:context.absolute_url()}/edit"
   class="pat-plone-modal"
   data-pat-plone-modal='{"actionOptions": {"reloadWindowOnClose": false, "redirectOnResponse": true, "disableAjaxFormSubmit": true},
                          "buttons": ".formControls > button",
                          "content": "#content-core"}'>
    Edit in a modal
</a>
```

**Comment by pbauer** [comment]
@petschki thanks, that indeed makes it work.

**Comment by akonstanczak** [comment]
Unfortunately this doesn't work well with collective.cover tiles. Even if I tweak edit button action (in compose view) as suggested form submit goes to separate, unstyled tile view which makes the whole UI unusable.

Also I cannot use this workaround when building complex widget with file upload modal. Cannot redirect editors to separate widget form upon file upload.

**Comment by thet** [comment]
Fixed in:‌ https://github.com/plone/mockup/pull/1186
Will be available after this is merged: https://github.com/plone/plone.staticresources/pull/232
