### ISSUE TITLE
relateditems: not orderable on existing content

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mockup#1205]
Tried in current Plone coredev 6, both with and without mockup in development mode, and in Plone 6.0.0a3 with the standard plone.staticresources for that version.

- Create a new page, do not save it yet.
- In the related items field add News and Events.
- Change the order of the two. This works.
- Save the page.
- Edit the page.
- Try to change the order of the two related items again. This fails. Nothing happens. The click is interpreted as: you want to add a new related item.

**Comment by petschki** [comment]
I can confirm on 6-classic.demo.plone.org ... but when editing the page, once you've added a new item, you can resort them again. Seems there are some initial select2 events missing when loading the page.
