### ISSUE TITLE
`pat-structure`: rename action titel field breaks if `"` is in title

### ISSUE THREAD

**Issue by petschki** [plone/mockup#1250]
`"` isn't escaped correctly for the rename action title field:

<img width="960" alt="Bildschirm­foto 2022-12-02 um 07 34 31" src="https://user-images.githubusercontent.com/511761/205230488-228aeddf-6a15-4a71-96a7-4b01e2b8db96.png">
<img width="525" alt="Bildschirm­foto 2022-12-02 um 07 34 45" src="https://user-images.githubusercontent.com/511761/205230493-680bc45a-a54d-4b07-9c1a-558b420a59b5.png">

**Comment by mauritsvanrees** [comment]
I confirm this is fixes by your PR #1252.
