### ISSUE TITLE
`pat-recurrence`: selected dates don't change when "Repeats" field changes

### ISSUE THREAD

**Issue by laulaz** [plone/mockup#1266]
When you add a recurrence to an event, and then change the repetition, the selected dates don't change.
You need to click in / change another field to make the selected dates list change.

Tested on Plone 6.0.0 final.

See this video, taken on demo :

![recurrence](https://user-images.githubusercontent.com/1101273/208922367-5dae8a1b-1df9-4581-8116-7075ba312f6a.gif)

cc @petschki

**Comment by petschki** [comment]
confirmed on https://classic.demo.plone.org ... I can take a look these days. There was some other issue with updating the dates when clicking the weekdays checkboxes which I fixed lately. Maybe I broke something there.
