### ISSUE TITLE
Login modal has doubled alert message

### ISSUE THREAD

**Issue by petschki** [plone/mockup#1273]
See https://classic.demo.plone.org/en/ and click login on top right.
<img width="515" alt="Bildschirm­foto 2023-01-25 um 10 21 17" src="https://user-images.githubusercontent.com/511761/214525792-584f878f-2348-47a5-94fb-5f91fc2b2b27.png">

The standard login_form only shows one message: https://classic.demo.plone.org/en/login

must be some selector mismatch/multimatch ...

**Comment by saadkhan011** [comment]
Hi, petschki,
   I want to work on this issue can you assign me this issue, please?
Thanks

**Comment by petschki** [comment]
@saadkhan011 we do not assign issues in general here. Just create a PR and add me as reviewer.

**Comment by saadkhan011** [comment]
Okay I am fixing this issue and I will let you know when it's done

**Comment by Pradeesh1430** [comment]
Hi, 

Can I Work on this?

**Comment by petschki** [comment]
Hi ... you need to read https://github.com/plone/mockup/blob/master/README.md#development how to setup this package for development. Unfortunately I do not have time to guide you through this... sorry.

**Comment by Pradeesh1430** [comment]
Thank you I'll go through that link and I'll Work on that.
