### ISSUE TITLE
wrong language selected in combination with p.a.contenttypes

### ISSUE THREAD

**Issue by agitator** [plone/mockup#355]
plone 4.3.3 with recent p.a.widget p.a.contenttypes
portal_language = de

when i create a new dx page, the language is not selected correctly and shows "Abkhazian"

![screen shot 2014-03-20 at 11 28 39](https://f.cloud.github.com/assets/365761/2470889/82cf0184-b01a-11e3-8893-332fcf03b354.png)

**Comment by vangheem** [comment]
Closing because this is stale. Please re-open if still a problem.
