### ISSUE TITLE
menus from plugins missing from structure

### ISSUE THREAD

**Issue by djay** [plone/mockup#385]
Certain plugins such as quintagroup.seoptimizer or [plonetemplates](http://plone.org/products/plonetemplates) create contextual dropdowns or tabs. In plone 4 users would switch to "contents", go to where they wanted and then use those functions to act on the current folder or page such as to create a templated page or edit the seo properties.
Currently Structure doesn't include these 3rd party tabs or drop downs however I think they appear on the toolbar "extras". That means you have browse using structure, then click "view" then drop out of structure and then click on the "..." and then use that plugin. It would be much nicer if instead those tabs and dropdowns were reproduced inside structure.

**Comment by vangheem** [comment]
Implementation is not done that same way previous way was done. Closing as invalid. This is now a plone.app.content documentation issue.
