### ISSUE TITLE
structure ignores mimetype of uploaded file to determine content type

### ISSUE THREAD

**Issue by djay** [plone/mockup#393]
This line ignores the mimetype and instead only uses filename to determine content type to use. 

https://github.com/collective/wildcard.foldercontents/blob/master/wildcard/foldercontents/views.py#L861

Instead it should be doing something more similar to https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/filerepresentation.py#L408

**Comment by vangheem** [comment]
Duplicate of https://github.com/plone/mockup/issues/394
