### ISSUE TITLE
Font size changed in foldercontent view

### ISSUE THREAD

**Issue by dgroos** [plone/mockup#411]
Upon clicking on "Contents" the popup opens but the font is very small (see image 1). Upon closing the folder contents popup, the font of the page stays small until the page finishes refreshing upon which it returns to its normal size. Using Plone 4.3.3 with following all install directions for foldercontent 2.0b3.

Image 1
![ss_539](https://cloud.githubusercontent.com/assets/4097759/4435006/9c0533a0-4730-11e4-91b7-f05698bcb789.png)

**Comment by vangheem** [comment]
closing as this is a specific problem related to wildcard.foldercontents 2.x and plone 4.x styles. I'm not currently working on this problem. Anyone want to pick up 2.x branch, feel free to reopen.
