### ISSUE TITLE
Seemingly incompatible between collective.lineage 1.1.1 and wildcard.foldercontents 2.0b3

### ISSUE THREAD

**Issue by dgroos** [plone/mockup#412]
No content is listed upon clicking on "Content" view of a folder in a child section of the site as shown in Image 1. Issue also posted here: https://github.com/collective/collective.lineage/issues/26

Image 1
![ss_538](https://cloud.githubusercontent.com/assets/4097759/4435024/517d7ada-4731-11e4-8f01-5b647f97adb2.png)

**Comment by vangheem** [comment]
I think this is fixed with this commit: https://github.com/plone/plone.app.widgets/pull/101
