### ISSUE TITLE
finish eventedit pattern for plone.app.event

### ISSUE THREAD

**Issue by thet** [plone/mockup#434]
the eventedit pattern was done at the zidanca sprint. it wasn't integrated in plone.app.event yet. main thing missing: adding a pat-eventedit class to the body or form of the edit form of an event....

**Comment by vangheem** [comment]
I'm going to close this issue. I think that the event edit pattern is unnecessary and I think I'm okay with how the event integration code is working right now: https://github.com/plone/plone.app.event/commit/e59fdd3a909ef4d9b64b94d05a9bb0e4f83a5997

**Comment by thet** [comment]
your fixes to the plone.app.event javascript are specially interesting, as they show off how to make legacy javascript work well with require js.

but i keep this eventedit pattern issue on my own todo agenda - the eventedit pattern is much better tested than the javascript in plone.app.event - which is not tested at all.
