### ISSUE TITLE
define "action" options raises error

### ISSUE THREAD

**Issue by petschki** [plone/mockup#450]
if you define the `action` option to override the `actionOptions` default values like

```
data-pat-modal='{"actions": {"displayInModal": false}}'
```

it raises a javascript error ... but if I define it this way:

```
data-pat-modal='{"actionOptions": {"displayInModal": false}}'
```

it works like it should ...

**Comment by vangheem** [comment]
Fixed docs here: https://github.com/plone/mockup/commit/878792367f7bc92a56020b37029e61ee84bf8717
