### ISSUE TITLE
Add recurrence widget pattern

### ISSUE THREAD

**Issue by thet** [plone/mockup#451]
a recurrence widget pattern is still missing for Plone 5. there is the legacy plone.formwidget.recurrence package, but it uses a unmaintained jQuery template lib and jquerytools datepicker. first one should be replaced by underscore's template functionality and latter with pickadate - or better yet lib-agnostic.

more ideas on how to improve can be found here: https://github.com/collective/jquery.recurrenceinput.js/issues

**Comment by jcbrand** [comment]
@thet This might be a good one to tackle at the Alpine Sprint.

**Comment by thet** [comment]
i agree

**Comment by fulv** [comment]
@thet Did any progress happen on this at the Alpine Sprint?  Either way, let me know, and I can help out.

**Comment by jcbrand** [comment]
@fulv Unfortunately not, all effort went into the Patternslib/Mockup merge.

**Comment by vangheem** [comment]
This is done.

**Comment by vangheem** [comment]
BTW, I did not replace the template lang or date picker for now. That widget is pretty crazy and that'd be quite a bit of work.

**Comment by thet** [comment]
awesome work, @vangheem ! you raised the plone 5 issue fixing rate a lot!
i'll keep the template and date picker refactoring issue on my internal todo queue.
