### ISSUE TITLE
pat-markspeciallinks does not allow the external_links_open_new_window behavior without also enabling mark_special_links

### ISSUE THREAD

**Issue by fulv** [plone/mockup#454]
re: https://github.com/plone/mockup/pull/429

We made a mistake in converting the legacy mark_special_links javascript into the corresponding markspeciallinks pattern.  The name of the legacy script was a little misleading, in that it actually encapsulated two different behaviors which are actually independent from each other:  
* `external_links_open_new_window` and 
* `mark_special_links`
In other words, it should be possible to enable either one or the other, or both, from @@theming-controlpanel.
Instead, the way the pattern is implemented now, the `external_links_open_new_window` behavior can only be enabled iff the `mark_special_links` behavior is enabled.  This, in turn, is enabled simply by giving the pattern class to an HTML element.  Thus, without the pat-markspeciallinks class, it would be impossible to activate the `external_links_open_new_window` behavior by itself.

I propose to fix this by introducing an additional boolean option `mark_special_links`.

FYI: @agitator

**Comment by jcbrand** [comment]
#454 has been merged, so this ticket can be closed, right?

I'll close it now. Please re-open if still valid.

**Comment by fulv** [comment]
Yes, I believe so.
