### ISSUE TITLE
moment-pattern does not use locales

### ISSUE THREAD

**Issue by pbauer** [plone/mockup#464]
While experimenting with replacing date-formating in plone.app.contenttypes with the moment-pattern (http://plone.github.io/mockup/dev/#pattern/moment) I realized that it does not use the current locales. This shoud to be done by default otherwise the pattern will be useless.

**Comment by vangheem** [comment]
Will it need to use plone locales or can we integrate with moment's locales?

**Comment by pbauer** [comment]
I doubt has Plone has same locales as moment.js since Plone has country-specific locales such as en_AU. We might have to map one to the other.

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/Products.CMFPlone/commit/87110c3c282d98093c3c1e208d0418394463aeeb
