### ISSUE TITLE
mockup will not build fresh right now...

### ISSUE THREAD

**Issue by vangheem** [plone/mockup#469]
This is supposedly the problem fixed: https://github.com/Patternslib/Patterns/commit/161aa5f43460d11d6709a40614caf81388543e1a

However, specifying patternslib version 2.0.9 in bower.json produces the error.

```
bower chosen#0.9.11                                       ENORESTARGET No tag found that was able to satisfy 0.9.11

Additional error details:
Available versions: 1.4.2, 1.4.1
make: *** [bootstrap] Error 1
```

@thet @bloodbare @jcbrand ideas?

**Comment by jcbrand** [comment]
I've been struggling with this issue for the last 2 days.

I created a bug report for chosen but they basically rejected it: https://github.com/harvesthq/chosen/issues/2294

A workaround is to identify all the dependencies where chosen#0.9.11 is being specified (in bower.json) and updating to a URL which resolves.

I updated mockup-core to Patternslib 2.0.9 yesterday and after doing that I was able to build it again. See here: 
https://github.com/plone/mockup-core/commit/0d9a9593314f62c12c63e62ba7c45b3219f7b41f

Is the solution perhaps for you to also use the latest mockup-core?

**Comment by jcbrand** [comment]
BTW, I'm on holiday from today until Tuesday when I'll be in Sorrento. I'd love to help out here but my time is currently very limited.

**Comment by vangheem** [comment]
@jcbrand thank you for tip--it's all I needed. I've updated the versions and created new tags.

**Comment by thet** [comment]
Which package is depending on chosen? If it's something under our control, maybe we should switch to select2.

However, for conflict resolutions, does something like this in bower.json help?
```
  "dependencies": {
  },
  "resolutions": {
    "chosen": "https://github.com/syslabcom/chosen.git#4371e8fdabe16d4e8aaa3734421edc367e32a296",
  }
```

**Comment by vangheem** [comment]
patternslib--we don't use it. BTW, this was fixed in master.
