### ISSUE TITLE
TinyMCE add link / upload

### ISSUE THREAD

**Issue by thet** [plone/mockup#471]
when adding a link in tinymce and using the upload feature in the add link dialog, after uploading nothing else happens. users think, it's already linked and close the add link dialog. instead, the file is only uploaded but the link is not created.

same issue is with the "insert image" dialog.

**Comment by vangheem** [comment]
I think I used to have this working but since the upload widget was updated, it no longer works.

Additionally, not sure what you do with multiple files uploaded.

**Comment by tomgross** [comment]
I can confirm this issue.

**Comment by thet** [comment]
A regression might be easier to fix than adding a new feature...

We should disallow multiple file uploads in this context. If there isn't, we'd have to add an option for single upload for the upload widget.
