### ISSUE TITLE
Syntax coloring

### ISSUE THREAD

**Issue by ebrehault** [plone/mockup#473]
In the theme mapper, the text editor must apply syntax coloring for HTML, JS, CSS and XML files.

**Comment by ebrehault** [comment]
The texteditor pattern does require 'ace-mode-text', 'ace-mode-javascript' and 'ace-mode-css' (so we miss HTML and XML), but they are not found when ACE tries to load them (so it calls a dummy url).

**Comment by vangheem** [comment]
hhmm, is this pointing to the right resources? https://github.com/plone/mockup/blob/master/mockup/js/config.js#L24

**Comment by ebrehault** [comment]
Yes, those pathes are correct.

**Comment by obct537** [comment]
This should be implemented by:
6184a03063c13fb84bcc51f2c158cdbdec2952d0

and the Products.CMFPlone commit:
572cd93eeb776783c5c31841187934f386fbfaa6
