### ISSUE TITLE
i18n can't find any element because its executed before loading the dom

### ISSUE THREAD

**Issue by bloodbare** [plone/mockup#482]
On https://github.com/plone/mockup/blob/master/mockup/js/i18n.js#L21 it causes problems because the dom is not accessible when is executed the i18n module. We should wrapp on document ready of some other idea.

@vangheem

**Comment by vangheem** [comment]
When I test it, the body tag is available to pull in the attribute. I can't reproduce this.

**Comment by frapell** [comment]
FWIW, I am too experiencing this issue. My solution was to put the compiled .js in the footer, because when it was at the header, the <body> was not there yet.

I am also using bootstrap, which does the same thing, so it wasn't a big deal

**Comment by vangheem** [comment]
weird. I can't reproduce it on latest. Also, I'm not sure how we'd be able to do anything on document load since this is necessary for other patterns that load translations not necessarily after document is loaded.

Even if we moved the logic to get the catalog url into the loadCatalog function, i18n-wrapper.js makes it a singleton and loads it right away.

**Comment by jcbrand** [comment]
I don't know this code well, but looks to me like the problem might be solved by evaluating ``self.baseUrl`` and ``self.currentLanguage`` more lazily, i.e. only when they are needed, which is in some of the methods and not when the module is instantiated.

**Comment by vangheem** [comment]
@jcbrand that is what I was referring to with:

> Even if we moved the logic to get the catalog url into the loadCatalog function, i18n-wrapper.js makes it a singleton and loads it right away.

Not sure this can easily be done. Still, I can't reproduce anyways.

**Comment by jcbrand** [comment]
@vangheem Thanks, I understand now.

**Comment by bloodbare** [comment]
It only happens some times, defitively when it reached the moment to get the catalog the body is not loaded. I'll try to spend some time to narrow down the workflow that triggers this issue.

**Comment by vangheem** [comment]
https://github.com/plone/mockup/commit/c56e3956e203c54c1f1e6c19c64fd4b9d0a13fd3 switched a bunch to load on initialization instead of using singleton... Does that help?

**Comment by jcbrand** [comment]
I understand that we need a solution here, but this change makes these patterns non-compatible outside of Plone and i18n.js, which is why I wrote the wrapper.

Could we instead add an **initialize** method to the wrapper which is called from the pattern. Then we have the best of both worlds.

**Comment by vangheem** [comment]
Ahh, I see now. I'll look into it more and revert this change.

**Comment by vangheem** [comment]
https://github.com/plone/mockup/commit/4558bccd01ce40e049ca96b55cc3d4d70ec23a06

Switched to lazy load the translate singleton.

**Comment by jcbrand** [comment]
nice one!

**Comment by bloodbare** [comment]
Uauu great one!
El dj, 16 abr, 2015 a les 14:23 JC Brand <notifications@github.com> va
escriure:
