### ISSUE TITLE
Remove pat-modal or rename it

### ISSUE THREAD

**Issue by jcbrand** [plone/mockup#483]
Currently we have a **pat-modal** pattern in both Patterns core and Mockup.

We can't have two different patterns with the same name in the same website. Ideally we want to remove the modal pattern from Mockup, but in the meantime I propose we rename it to something else, to at least avoid this naming conflict.

This will gives us some breathing space until we can eventually replace it with the one from Patterns.

Can I rename it to pat-mockup-modal, or pat-plone-modal?

**Comment by vangheem** [comment]
That's fine. Rename it to pat-plone-modal. There are a few places in Plone
core where it is used that will need to be updated.
