### ISSUE TITLE
Tests hang 

### ISSUE THREAD

**Issue by fulv** [plone/mockup#487]
When I run `make test`, it always hangs at 

`PhantomJS 1.9.8 (Mac OS X): Executed 236 of 238 (skipped 2) SUCCESS (10.046 secs / 8.342 secs)`

Not sure what that's about.

**Comment by vangheem** [comment]
It's not hanging, it's waiting for you to make code changes and then it
will automatically run tests again. Use "make test-once" to just run one
time.

**Comment by fulv** [comment]
D'oh!
Thanks!  I'll make sure it's documented.
