### ISSUE TITLE
upload dropzone is always active

### ISSUE THREAD

**Issue by domruf** [plone/mockup#493]
There are a few places like
```
  if(!self.options.upload){
  ...
```
but because upload has a default value AFAICS self.options.upload is always true.
Either the "With dropzone" example should be removed and the code should be cleaned up or the if statements should be fixed.

**Comment by vangheem** [comment]
I think we should just have these sort of things as hard dependencies and not options.

**Comment by domruf** [comment]
In that case should I create a pull request to makes my pr #492 non optional?

**Comment by vangheem** [comment]
Yes, it's fine though. We can change it. Or you can introduce another pull request :)
