### ISSUE TITLE
structure: item selection is too persistent, lock selections until action is completed

### ISSUE THREAD

**Issue by thet** [plone/mockup#507]
A client fell into this pitfall: He selected a folder with lots of contents, cut it, navigated somewhere else, pasted it, navigated back, selected something, deleted it and both selected items were lost and the copy task couldn't finish.

Here are two problems:
1) Selections should be cleared, after a successfull actions was performed. ~~Or it should be made clear, that there is still a selection active (a message box with a link to a list of items...?)~~ << oh, that's already implemented...
2) Cut, copied or deleted items should be greyed-out and locked from further actions until the cut/paste/delete action (or any other) is canceld or finished.

**Comment by vangheem** [comment]
Definitely. Selection should be cleared after any action IMO.

**Comment by vangheem** [comment]
done with latest
