### ISSUE TITLE
Y-scroll disappears when closing a modal within a modal 

### ISSUE THREAD

**Issue by frapell** [plone/mockup#508]
Steps to reproduce:

1) Open a modal that contains a TinyMCE
-- The scroll for the whole page is replaced so the modal scrolls and not the whole page --
2) Open the "Insert Link" modal
-- Scroll is not available since this modal is small --
3) Close the "Insert Link"

At this point, you no longer have a scroll for the big modal. I haven't yet found what is the *exact* cause of this, but I think it has something to do when from the _show method from the modal pattern, there's a line ```self.$wrapper.parent().css('overflow', 'hidden');```, and later, from the hide method

```
if ($('.plone-modal', self.$wrapper).size() < 2) {
    self.backdrop.hide();
    self.$wrapper.hide();
    self.$wrapper.parent().css('overflow', 'visible');
}
```

In my use case, I am actually extending mockup, and what I did to solve it was to add:
```
$(window.parent).on('hidden.plone-modal.patterns', function() {
    // Make sure overflow-y still visible for parent modal (if any)
    $('div.plone-modal.fade.in').css('overflow-y', 'visible');
});
```

**Comment by vangheem** [comment]
@frapell I think it's the class plone-modal-open on the body class that you need to take a look at. 

I think the line:

$('body').removeClass('plone-modal-open');

Should be moved within this:

if ($('.plone-modal', self.$wrapper).size() < 2) {

in the hide method of the modal pattern. Can you take a look?
