### ISSUE TITLE
pat-passwordstrength: Error: Mismatched anonymous define()

### ISSUE THREAD

**Issue by Gomez** [plone/mockup#512]
I included the passwordstrength pattern in Plone 5.0b2 like this (registry.xml ):

```
  <records prefix="plone.resources/pat-passwordstrength"
           interface='Products.CMFPlone.interfaces.IResourceRegistry'>
    <value key="js">++resource++mockup/passwordstrength/pattern.js</value>
    <value key="css">
     <element>++resource++mockup/passwordstrength/pattern.passwordstrength.less</element>
    </value>
 </records>
```

then just added this simple HTML to on of my templates:

```
<input type="password" class="pat-passwordstrength" />
```

This JS error appears:

Error: Mismatched anonymous define() module: function ($, Base, undefined) {...

Something wrong with my includes? Other patterns (like datepicker) works otb.

**Comment by vangheem** [comment]
How are you including it?

Adding the resource to the registry does not mean it'll be pulled in by any bundle.

You'll need to create your own bundle file that will have a "require" statement to include that pattern so it's loaded. Use that bundle in dev mode or build a production version of it.

Example bundle file:

```
require(['pat-passwordstrength'], function(){});
```

Or you can modify an existing bundle file to include it.

**Comment by Gomez** [comment]
Thanks @vangheem! 

The "require" statement was the missing piece. 
I close as this is not a bug (will do some docu, later).
