### ISSUE TITLE
AjaxSelectWidget: Saved Value from SimpleVocabulary displayed wrong

### ISSUE THREAD

**Issue by pbauer** [plone/mockup#519]
AjaxSelectWidget displays the value instead of the tile of a item from a SimpleVocabulary. 

To reproduce create a dx-content type wit a field using the AjaxSelectFieldWidget and a SimpleVocabulary. 
```python
DummyVocabulary = SimpleVocabulary(
    [SimpleTerm(value=u'gold', title=_(u'Gold Sponsor')),
     SimpleTerm(value=u'silver', title=_(u'Silver Sponsor'))])
```

Use it in a schema:

```python
dummyfield = schema.List(
    title=_(u'Dummy'),
    value_type=schema.Choice(
        title=_(u'Dummy'),
        vocabulary=DummyVocabulary),
    required=False,
)
form.widget(
    'dummyfield',
    AjaxSelectFieldWidget,
    vocabulary=DummyVocabulary,
)
```

When I edit the field I see the correct options (e.g. "Gold Sponsor"). That is also used when I select a value. But after saving a value and when re-editing the object the saved value displayed in the field will now be "gold" instead of "Gold Sponsor". 

The problem does not appear when using a NamedVocabulary:

```python
@implementer(IVocabularyFactory)
class DummyVocabulary(object):

    def __call__(self, context):
        return SimpleVocabulary([
            SimpleTerm(value=u'gold', title=_(u'Gold Sponsor')),
            SimpleTerm(value=u'silver', title=_(u'Silver Sponsor')),
        ])

DummyVocabularyFactory = DummyVocabulary()
```

registered like this:

```xml
  <utility
    component=".dummy.DummyVocabularyFactory"
    name="mypackage.DummyVocabulary"
    />
```

Used in the schema like this:

```python
dummyfield = schema.List(
    title=_(u'Dummy'),
    value_type=schema.Choice(
        title=_(u'Dummy'),
        vocabulary='mypackage.DummyVocabulary'),
    required=False,
)
form.widget(
    'dummyfield',
    AjaxSelectFieldWidget,
    vocabulary='mypackage.DummyVocabulary',
)
```

**Comment by vangheem** [comment]
I think you want to use SelectFieldWidget instead of the ajax widget. ajax widget is for dynamic vocabularies.

**Comment by pbauer** [comment]
@vangheem you are right. ``SelectFieldWidget`` works perfectly with a static vocabulary.

**Comment by thet** [comment]
sounds a bit as if it would be related to https://github.com/plone/plone.app.content/pull/34 " Fix encoding problems with Mockup Select2 widget" where I was probably doing a mistake. don't know yet, though.
