### ISSUE TITLE
Make a stronger warning in folder contents' Rearrange popover

### ISSUE THREAD

**Issue by davilima6** [plone/mockup#526]
Make **a stronger warning about this being permanent** and not about [old sorting] feature, linked to a routine that closes that popover and opens the correct `Query` one.

That'd be similar to the `If you wanted to edit the container itself, go here` status info which is displayed when you edit a default view of a container.

**Comment by agitator** [comment]
we could make the already existing warning more prominent, for example red
but please no additional click

**Comment by davilima6** [comment]
Not red, bold should be enough. The extraclick is a redirection commodity to minimize confusion problems during the new UI learning phase.
