### ISSUE TITLE
Cannot upload file during archetype creation

### ISSUE THREAD

**Issue by Gagaro** [plone/mockup#528]
Hi,

If we try to link and upload a file in a RichText field and on a folderish ATCT, the creation will fail with an AttributeError. First I was thinking to only hide the upload during AT creation, but if we are creating a non-folderish object, we should be able to upload in the parent object like it used to be.

So what I'm thinking now would be to enable the upload in the cases of a non-folderish, but to actually upload in the parent. The upload would still be disable for folderish with a message explaining what's going on.

I started to work on my first idea [there](https://github.com/plone/mockup/tree/fix-archetype-creation). The issue with my new idea would be to get the information about the object being or not folderish. What would be the better solution, an ajax call giving me this information ? Or could I get it another way ?

What do you think about all that ?

cc @ebrehault

**Comment by vangheem** [comment]
I think this has been fixed for a while. Are you working on plone.app.widgets on plone 4? If so, I don't know the state of that. At this point, I can only really support plone 5.

**Comment by Gagaro** [comment]
Sorry I forgot to precise, it's for plone 5.

**Comment by vangheem** [comment]
hhmmm, okay. It should just go to parent to upload to.

**Comment by Gagaro** [comment]
What do you think the best way to determine if the CT is folderish or not would be ? Will something like this be ok (an call to a browser view in Products.Archetypes ?):

```
{
    "folderish": true,
    "upload_to": "/Plone/parent_dir/"
}

**Comment by vangheem** [comment]
I think you want to look here: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/patterns/__init__.py#L221

I think we're missing a check if it's archetypes temporary folder.

**Comment by Gagaro** [comment]
Thanks it looks like where it should be fixed.

What about folderish ATCT, should we upload in the parent during creation and in the content during edit ? It would allow the upload to works every time but a change in behavior could be strange for users.

**Comment by vangheem** [comment]
Yes, I think that is probably fine.

**Comment by Gagaro** [comment]
I tried modifying `currentPath` in the configuration but the one I have in `data-pat-tinymce` and the one I get in the `UploadPattern` are different. Do you know what's going on ?

**Comment by vangheem** [comment]
you can make sure this is working properly: https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/Widget.py#L1365

**Comment by Gagaro** [comment]
Pull request for Products.CMFPlone: https://github.com/plone/Products.CMFPlone/pull/694
