### ISSUE TITLE
create a pattern like stacks

### ISSUE THREAD

**Issue by domruf** [plone/mockup#532]
I think of something like http://patternslib.com/demo/stacks/index.html
And I believe the functionality is already available, because the navigation bar is using something similar.
But I can't find any documentation on how to use it.

**Comment by vangheem** [comment]
Use pat-autotoc: http://plone.github.io/mockup/dev/#pattern/autotoc

See the tab example.

**Comment by domruf** [comment]
okay thanks
it didn't came to me that this could be part of the autotoc pattern
