### ISSUE TITLE
Make view-icon in tablerow.xml translatable 

### ISSUE THREAD

**Issue by pbauer** [plone/mockup#537]
`title="View"` in `mockup/mockup/patterns/structure/templates/tablerow.xml` is not translatable. 
I tried it by replacing it with `title="<%- _t('View') %>"` and amending `tablerow.js` to support `_t` but failed :cry:

**Comment by vangheem** [comment]
Does this work: https://github.com/plone/mockup/pull/539 ?

I didn't test myself so if you can, that'd be great!

**Comment by pbauer** [comment]
That works \o/
There is a insane number of layers of caching to work around when trying it out:

- bundle (enable dev-mode for plone and plone-logged-in resources)
- the js (reload http://localhost:8080/Plone/++resource++mockup/structure/js/views/tablerow.js in the browser or disable browser-cache)
- the xml-file (reload http://localhost:8080/Plone/++resource++mockup/structure/templates/tablerow.xml  in the browser or disable browser-cache)
- the mo-file (restart the instance to recompile it)
- the widgets-locales (localStorage.clear() in the browser-console takes care of that) 

Forget one of these and you'll not see the current state fo the code.

**Comment by vangheem** [comment]
What might help is to always disable caching when you have developer tools open.

**Comment by vangheem** [comment]
but yah, you have to clear localstorage too :(
