### ISSUE TITLE
image pasting does not work

### ISSUE THREAD

**Issue by vangheem** [plone/mockup#543]
@domruf I tried activating the image pasting feature you implemented and it's very broken.

I'm not even sure how it's supposed to work. Shouldn't it upload immediately after being pasted? Currently it shows an empty upload dialog and when you click "insert" it throws an error.

I don't have a problem with the native tinymce paste implementation of pasting data:uri images either--that is more intuitive for users.

Do you have any idea what is going on? While the feature isn't active by default, I will probably remove the code/feature if a fix isn't provided.

Let me know your thoughts.

**Comment by vangheem** [comment]
https://github.com/plone/mockup/pull/546 please add back with fixes if you're interested still! Sorry that this feature didn't get any love but it's really broken right now.

**Comment by domruf** [comment]
@vangheem the intended behavior is that the upload dialog opens and you can choose a different folder before uploading.
It should be that same as when you try to upload a file by dropping it in the upload dialog.

Did the upload button not appear for you? That browser did you use?
You are right, when someone clicks "insert" the upload should also start.

I will make same improvements, make more tests and create a new pull request.

**Comment by vangheem** [comment]
Thanks @domruf 

I'm sorry I had to rip it out. It just wasn't working and I wasn't sure about the implementation.

I almost thought it was better for on paste to not upload but to just embed data URIs instead.
