### ISSUE TITLE
Collection: 'any' Creator search term gets no dropdown

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/mockup#557]
Fresh Plone 5 coredev. Create a Plone Site. Create a Collection. In the search terms add 'Creator' and 'Matches any of'.

Expected: a dropdown with possible authors, in this case only 'admin'. Or maybe an autocomplete field.

Actual: the field for the value stays empty. Typing in it has no effect.

See screenshot.

![schermafbeelding 2015-08-21 om 18 18 29](https://cloud.githubusercontent.com/assets/210587/9413750/2f1cf664-4834-11e5-90f2-f0cb2d169c94.png)

**Comment by vangheem** [comment]
Do you have any users on your site?

The user vocabulary does not include the root admin user so you always have to create users.

**Comment by mauritsvanrees** [comment]
In this site not, but I had the same earlier today with a site that did have multiple users and multiple creators.

This should not load the user vocabulary, but a vocabulary based on the Creator index in portal_catalog.

I don't really know whether this is something in mockup or elsewhere.

**Comment by vangheem** [comment]
I think it's using: https://github.com/plone/plone.app.vocabularies/blob/master/plone/app/vocabularies/users.py

If you want it to use the creator index, we'll need a new vocabulary.

**Comment by mauritsvanrees** [comment]
I just created a second user just in case. A real Plone user, with site admin rights. I added a page as this user. He does not show up in any dropdown.

Maybe related: javascript console in Firefox says seven times: "patterns.Mockup Base: This mockup pattern without a name attribute will not be registered!"

**Comment by vangheem** [comment]
No, that logging message is harmless and has nothing to do with it.

**Comment by vangheem** [comment]
Okay, I see. No vocabulary is used. That field was always just a free-text field. For the "Any" variant, a user should be able to enter a list of users. What would be nice is to be able to auto-complete available users; however, it seems like that was never implemented that way.

So yes, it's a bug. The widget doesn't allow any values no matter what.

**Comment by vangheem** [comment]
Trying to use the tags criteria also suffers from the same problem.

**Comment by mauritsvanrees** [comment]
The 'any' option was added to plone.app.querystring just today. There was a related pull request in mockup that got merged, but that seems to have been for a different part, with dates.

Note that the 'any' option is working fine for review state.

**Comment by vangheem** [comment]
It seems workflow_state works because plone.app.querystring plone.app.querystring.field.review_state field defines a vocabulary. 

plone.app.querystring.field.Creator does not.

**Comment by vangheem** [comment]
See https://github.com/plone/plone.app.querystring/tree/add-user-vocabulary 

I think we should get rid of plone.app.querystring.operation.string.is and just allow the plone.app.querystring.operation.selection.any to take care of it.

**Comment by mauritsvanrees** [comment]
Ah, right. Then it works.

We may need a real Creator vocabulary, but yes, when I try it with the Users vocabulary it works.

Cool. All is well in mockup then, so I'll close this issue. Thanks.
