### ISSUE TITLE
Pickadate has no visual indication when input data is incomplete and would not be submitted

### ISSUE THREAD

**Issue by do3cc** [plone/mockup#576]
See also: https://github.com/plone/Products.CMFPlone/issues/271
The expires field uses a Pickadate pattern. Only selecting a date and saving will result in the date being silently discarded. This is because the widget data is only updated if both time and date is set.
If one only sets a time value, it is hard to decide what a good default value might be for date.
So maybe the pickadate widget should have a visual indication if data is incomplete and would not be saved.

**Comment by cekk** [comment]
I have a similar problem (with last mockup version) with start and end date in events (plone.app.event).
If i clear the hour from the widget, and try to set "whole day" (so it shouldn't need the hours), i have a validation error and when i'm redirected to the form, the fields are empty (also the date).

Are they related problems?
Is it resolved in some package upgrade?

**Comment by keul** [comment]
I think this bug is quite critical, it's generating this side effect: https://github.com/plone/Products.CMFPlone/issues/1006

**Comment by tomgross** [comment]
We are hit by this bug too since a long time. Anything I can help to fix it?

**Comment by thet** [comment]
- Maybe another invariant, checking for a valid date could solve it: https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/behaviors/metadata.py#L166

- Or a field/widget converter, which does the check.

- Or a JavaScript, which sets some default values, if a date or time are changed, but the other one isn't set yet (like it's done in plone.app.event).

Would be great if someone could work on it.

**Comment by adrianschulz** [comment]
I had nearly the same problem as @cekk and while analysing I noticed that in the HTML-code the value of the datepicker is not written in the "data-value"-attribute.

**Comment by tomgross** [comment]
It has to be JavaScript. With JavaScript turned off it works.

**Comment by thet** [comment]
Fixed here Plone 5.1: https://github.com/plone/mockup/pull/726 and Plone 5.0: https://github.com/plone/mockup/pull/727
