### ISSUE TITLE
404 on pat-base.js

### ISSUE THREAD

**Issue by Gagaro** [plone/mockup#589]
Hello,

I have an issue when I have the plone-logged-in bundle in develop mode. I have a 404 on pat-base.js. I did a bower install to have all resources.

After bissecting, it seems to have be cause by the following commit: 8d616f966c016c7d26223d6c8d3d3aa70e8aaa56

Did I miss a step ?

Thanks.

**Comment by jcbrand** [comment]
Looks like you don't have the path to pat-base configured.

Do you use custom patterns not included in the mockup egg?
If so, then those patterns probably have their own config file for specifying the paths of the JS dependencies. You then just need to add a path for pat-base as well.

Check in mockup/js/config.js for an example.

**Comment by vangheem** [comment]
Products.CMFCore was never updated with the new base pattern I think.

**Comment by vangheem** [comment]
Never mind, Plone never updated to latest mockup(which is a good thing at this point) so we're fine.

**Comment by Gagaro** [comment]
I don't have any custom mockup that I know of. Is there a way to trace it ? The errors I have only point to require.js.

**Comment by jcbrand** [comment]
From what @vangheem says, sounds like you need to add the path to Products.CMFCore. If you do a grep there for pattern names you'll probably quickly find the file where the paths are configured, then just add a path for pat-base as well.

If it works, please make a pull request.

**Comment by Gagaro** [comment]
I tried adding it to Products.CMFCore but it still doesn't work.

Also `pat-base` is not in the `config.js` file I get in the browser. How is this file generated ?

**Comment by jcbrand** [comment]
I can't say. I'm not familiar with how those things are done in Plone nowadays.

**Comment by vangheem** [comment]
I'm sorry, I meant the latest Products.CMFPlone

We'd just need to add a registry entry for pat-base in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/dependencies/registry.xml

Not sure this is your problem though.

**Comment by jcbrand** [comment]
This is almost certainly a path issue.

**Comment by Gagaro** [comment]
@vangheem I added the resource TTW (I'm not so sure how to apply this profile) and it seems to work. PR is there: https://github.com/plone/Products.CMFPlone/pull/1106
