### ISSUE TITLE
settings in tinymce control panel > Plug ins and  Toolbar  are totally neglected

### ISSUE THREAD

**Issue by fgrcon** [plone/mockup#595]
plone 5 /current coredev
check/uncheck any of rthe boxes and save: no reaction at all !
even worse from a user experience view: https://github.com/plone/mockup/issues/594

**Comment by vangheem** [comment]
This isn't a mockup issue.

However, before you reopen, this looks like a duplicate of: https://github.com/plone/Products.CMFPlone/issues/806

**Comment by vangheem** [comment]
reopen in CMFPlone if you still think it is an issue.
