### ISSUE TITLE
autotoc pattern screen jumps to clicked tab element

### ISSUE THREAD

**Issue by polklibrary** [plone/mockup#601]
The autotoc has no option to prevent the screen from jumping down to the toc head.  There are easing options but nothing to prevent the screen from moving or jumping down the tab element you just clicked.  It is happening because it makes anchor elements with href="#autotoc-item-autotoc-1".   There needs to be a way to prevent this.

**Comment by vangheem** [comment]
https://github.com/plone/mockup/commit/22617225d4b3be293de124d7d1755da080ef2f9d fixed this. This will be fixed in Plone 5.0.1 when it is released.
