### ISSUE TITLE
The visual editor TinyMCE is no matter js equivalent language of the site.

### ISSUE THREAD

**Issue by hersonrodrigues** [plone/mockup#609]
In my case I set for the language of Brazil (pt_BR), but the js that is required is called pt-br.js. Inside the langs folder, there's a file called pt_BR.js which is obviously not found, because the name is very different.

**Comment by neilferreira** [comment]
I am noticing the same thing.  

My website is 404ing on /++plone++static/components/tinymce-builded/js/tinymce/langs/en_EN.js

**Comment by petschki** [comment]
See #849
