### ISSUE TITLE
"Develop CSS" and "Develop JS" are disabled when the resource is selected

### ISSUE THREAD

**Issue by ebrehault** [plone/mockup#633]
See https://github.com/plone/Products.CMFPlone/issues/1392

It can be reproduced on the mockup demo http://plone.github.io/mockup/dev/#pattern/resourceregistry

**Comment by vangheem** [comment]
Ah, thanks for figuring this out. I couldn't reproduce it.

**Comment by vangheem** [comment]
https://github.com/plone/mockup/pull/634
