### ISSUE TITLE
Let ``pat-plone-modal`` add ``ajax_load=1`` to URLs by itself.

### ISSUE THREAD

**Issue by thet** [plone/mockup#649]
When opening portal_action links in a modal, we have to make sure to add `ajax_load=1` to the anchor's href attribute by ourselves. Like here:
https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L374

But here it looks like it was forgotten (or is that intentional?):
https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L264

If we let `pat-plone-modal` to add `ajax_load=1` by itself, we 1) cannot forget it anymore, 2) we're able to open the links in a new tab without being stripped down by the ajax_load parameter.

Possibly we should make this configurable (with default=True, which isn't the current behavior  but optimizes load times).

**Comment by pbauer** [comment]
I'm -1 If we'd use `ajax_load=1` by default it would mean we're only able to include stuff that is within `#content` in a modal. Last weak I had a project where the comments are be added in a modal and they are not within `#content`.

**Comment by thet** [comment]
For your use case, you could use the configurable option.
Or we do the other way around - all modals which need ajax_load need to get configured so.
IMO we should not let Plone render the links with ajax_load but mockup should do that. Otherwise you don't get useful results, when opening these links in a new tab/browser window.
