### ISSUE TITLE
Paste button in folder_contents does not become enabled in firefox and chrome

### ISSUE THREAD

**Issue by martior** [plone/mockup#664]
After copying from one folder and navigating to the next in folder contents, the paste button does not become enabled in firefox and chrome. It works in safari. If you press any of the check boxes, either check all or another content item it becomes enabled.

**Comment by vangheem** [comment]
Already fixed here: https://github.com/plone/mockup/commit/f8e85e2db269e1e591316200057574519fbd76f8

**Comment by martior** [comment]
sorry, should have checked commit log too, only checked issues.
