### ISSUE TITLE
copy a item and switch to another folder in folder_contents view ,paster button still can't be actived

### ISSUE THREAD

**Issue by adam139** [plone/mockup#674]
I have readed [the issue 664](https://github.com/plone/mockup/issues/664) and updated mockup to github master version. 
Plone:CMFPlone 5.0.2
browser: firefox

**Comment by vangheem** [comment]
Please do not create a new issue if it's already been closed. You can comment on the previously closed issue before you create another.

Did you also re-build the plone-logged-in bundle?

**Comment by adam139** [comment]
Sorry,I forgot to  rebuild the plone-logged-in bundle. after rebuild it,work fine.
