### ISSUE TITLE
lost i18n machanism in some xml templates or how to translate these messages in them?

### ISSUE THREAD

**Issue by adam139** [plone/mockup#677]
![insertimage](https://cloud.githubusercontent.com/assets/1474673/15573836/55adebac-237c-11e6-9706-3774021a9815.jpg)
I have found some text messages can't be translated in the [xml template files,for example: image.xml](https://github.com/plone/mockup/blob/master/mockup/patterns/tinymce/templates/image.xml)

**Comment by vincentfretin** [comment]
This message has long been translated. Closing this.
