### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by cekk** [plone/mockup#681]
Hi, today i've lost some time trying to use the pat-tablesorter pattern showed in the documentation.
After some time, i've digged a bit and i've found an old pr (#540) that removed it from the core.

Could it be a good idea to update the documentation with the updated state of patterns?
As i remember from the Bristol's training, this should be generated automatically..or not?

**Comment by vangheem** [comment]
Thanks for the heads up.

I've updated the docs now.

This is a manual command we need to run right now unfortunately so it isn't automatically generated on each commit(would be nice if it was).

http://plone.github.io/mockup/dev is updated to latest now.

**Comment by gforcada** [comment]
@vangheem would that be something that mr.roboto could do? Or credentials and such are needed?

**Comment by vangheem** [comment]
@gforcada Just need to be able to commit to the branch `gh-pages`.

**Comment by gforcada** [comment]
@vangheem that should be *easy* (famous last works, but hey, let's be optimist :D) would you mind creating a ticket at [mr.roboto issue tracker](https://github.com/plone/mr.roboto/issues) with all the needed information?

**Comment by vangheem** [comment]
done, thanks.
