### ISSUE TITLE
Structure's Paste button doesn't follow Toolbar's Paste action availability

### ISSUE THREAD

**Issue by davilima6** [plone/mockup#682]
Steps to reproduce:

1. Cut or copy the source items using the toolbar or the ZMI.
2. Change your browser URL or use the main menu/any of the global viewlets to navigate to desired target.
3. Click toolbar's `Contents`.
4. Notice the Paste button holds the class "disabled".

A broader usecase:

1. Cut or copy the source items using Structure pattern.
2. Leave the page and return.
3. Notice Paste button is disabled. It doesn't check to see if there are items in the "clipboard", as expected and in accordance to toolbar's `Action` item and to Plone 4.

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/mockup/commit/f8e85e2db269e1e591316200057574519fbd76f8
