### ISSUE TITLE
Structure's Paste button isn't disabled when clipboard is empty

### ISSUE THREAD

**Issue by davilima6** [plone/mockup#683]
In Plone 4 we had this portal message: `The item you are trying to paste could not be found. It may have been moved or deleted after you copied or cut it.` It's also in Plone 5 if you just use the toolbar.

Structure patterns only gives a general JS alert: "There was an error performing this action".

Best scenario would be disabling Paste when "clipboard" is empty but at least an informative proper portal error msg would help.

**Steps to reproduce:**

1. Click Contents in any folder and **cut** one or more items using the Structure pattern.
2. Navigate to another folder.
3. Click Structure's Paste button. It works.
4. Click it again. You get the alert and the following traceback:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.contents.paste, line 42, in __call__
  Module OFS.CopySupport, line 205, in manage_pasteObjects
CopyError: 
<HTML>
<HEAD>
<TITLE>Item Not Found</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF">
<FORM ACTION="manage_main" METHOD="GET" >
<TABLE BORDER="0" WIDTH="100%" CELLPADDING="10">
<TR>
  <TD VALIGN="TOP">
  <BR>
  <CENTER><B><FONT SIZE="+6" COLOR="#77003B">!</FONT></B></CENTER>
  </TD>
  <TD VALIGN="TOP">
  <BR><BR>
  <CENTER>
  One or more items referred to in the clipboard data was not found. The item may have been moved or deleted after you copied it.
  </CENTER>
  </TD>
</TR>
<TR>
  <TD VALIGN="TOP">
  </TD>
  <TD VALIGN="TOP">
  <CENTER>
  <INPUT TYPE="SUBMIT" VALUE="   Ok   ">
  </CENTER>
  </TD>
</TR>
</TABLE>
</FORM>
</BODY></HTML>
```

**Comment by vangheem** [comment]
Fixed here: https://github.com/plone/mockup/commit/f8e85e2db269e1e591316200057574519fbd76f8

**Comment by davilima6** [comment]
I just tested and this and #682 aren't fixed in 5.1 branch. Did you test it today?

**Comment by vangheem** [comment]
Resources just weren't built for a while. It was already fixed in mockup though. I have PRs for 5.0 and 5.1 to update the built js/css resources from mockup.

**Comment by davilima6** [comment]
I see, however I just switched to `build-resources-5.2` branch and could reproduce both issues (no buildout rerun, just cleared cache). We can wait for those PRs to be merged and test again, though.

**Comment by vangheem** [comment]
with the new bundle merging, you need to either run an upgrade that causes re-merging or go into resources registries and toggle dev mode on/off.

**Comment by vangheem** [comment]
unless you were on a new site, then it should be fixed.

**Comment by davilima6** [comment]
Yes, I reported this issue based on a brand new site from a just pulled buildout.coredev 5.1 branch. And then also tested on the build-resources-5.2 branch.

**Comment by vangheem** [comment]
Okay, I see the problem. `mockup` wasn't in the checkouts when I ran the build.

**Comment by vangheem** [comment]
And also, at some point mockup got branched to 2.1.x and I didn't notice.

**Comment by vangheem** [comment]
@esteele looks like you branched it. Is there a particular reason why? I'd prefer not to maintain 2 branches if we can help it.

**Comment by davilima6** [comment]
@vangheem, @gforcada: would it be possible/desirable to have mr.roboto run the compile bundles step once it detects any successfully merged PRs modifying related sources?
