### ISSUE TITLE
un-gitignore bower_components

### ISSUE THREAD

**Issue by thet** [plone/mockup#688]
@vangheem @pilz @bloodbare @jensens 

I dislike the Products.CMFPlone static/components folder, which is most often not in sync with current mockup development.

What about removing it and instead git-commit-push mockups bower_components (possibly renamed to just ocmponents)? mockup is a core dependency of Plone anyways, and the 50 MB payload shouldn't be that problem. We would not need to keep cmfplone's components directory in sync with mockups. And we might possibly make plone.patternslib obsolete, because we already have these in mockup.

Further thinking, maybe we should then move all resource definitions from CMFPlone's dependencies/registry.xml into a newly to-be-created mockup profile.

I would also move the toolbar pattern into mockup.

Anything against something like this?

I would target Plone 5.1 - so now it's the time for it.

Should that be PLIP'd?

**Comment by frapell** [comment]
A big +1 from me for the static/components folder and moving resource definitions away from registry.xml

And yeah, I think it should be plip'd...

**Comment by bloodbare** [comment]
about plone.patternslib i'm agree.

About the mockup repository and CMFPlone:

It was designed that the mockup respository is javascript oriented and its not a generic setup package. In my opinion, the JS that are included in Plone should be in CMFPlone and the mockup repository be a place to develop a group of patterns that are used on Plone. The only inconvenient is that upgrades on base js libraries needs to be in sync on CMFPlone, and in my opinion it should be like that as lots of addons needs to know which versions of JS are going to be deployed on their loved Plone core and makes sense that is on CMFPlone as the main core package.

That also applies to registry.xml, you need to commit to cmfplone to change js dependencies on Plone.

About the toolbar I think is interesting to have it on CMFPlone to show a core example of a out of mockup pattern.

**Comment by thet** [comment]
@bloodbare mockup is already a python package - all the patterns are served from there. by specifying the mockup verison you also get a defined set of javascript versions.

IMO the current situation is a mess. CMFPlones components directory is already out of sync. mockup-core is in there, which isn't used since mockup 2.0. the provided patternslib is outdated, which leads to problems when using plone.patternslib. and the toolbar could use more love. 

currently i would recommend to write generic patterns the patternslib way, because that way we find a bigger user base. mockup is plone-only. so I wouldn't recommend the toolbar as best practice.

**Comment by thet** [comment]
now discussed at: https://github.com/plone/Products.CMFPlone/issues/1644
