### ISSUE TITLE
tests status

### ISSUE THREAD

**Issue by gforcada** [plone/mockup#693]
Hi mockup devs,

I see that [travis seems to not be active](https://travis-ci.org/plone/mockup) and since quite a few weeks jenkins.plone.org is also [not able to run tests of mockup](http://jenkins.plone.org/job/plone-5.1-js), so I'm wondering what's the status of mockup regarding testing, is anyone caring for it, where is the continuous integration done right now (as both travis and jenkins.plone.org are not doing it at all)?

Could someone shed some light on how to fix the [current failure on jenkins.plone.org](http://jenkins.plone.org/job/plone-5.1-js/18/console)? I updated node to its latest LTS (4.4.7) if that helps.

@vangheem @thet @jcbrand @frapell @bloodbare just to name a few top contributors...

**Comment by vincentfretin** [comment]
The js tests doesn't appear to be running on jenkins anymore. The tests run currently on travis though.
