### ISSUE TITLE
Mark special link pattern not recognize the # on https

### ISSUE THREAD

**Issue by keul** [plone/mockup#707]
In a Plone site served on HTTPS where the mark special link pattern is enabled, every link that starts with `#` is marked as a "special".
This also happen with Plone pages like the theming controlpanel:

![schermata 2016-09-09 alle 10 26 06](https://cloud.githubusercontent.com/assets/284924/18380502/eb8fb2c4-7677-11e6-8896-f3d7aeccb1d5.png)

**Comment by vangheem** [comment]
In addition to this issue, mark special links should only do it to the content body of the page, not the entire page like it does now.

**Comment by vangheem** [comment]
I actually can't reproduce your issue; however, I have provided PRs for only doing it on the content of the page

https://github.com/plone/mockup/pull/709
https://github.com/plone/mockup/pull/708

**Comment by fulv** [comment]
I can see this issue, too.

- Plone 5.0.6
- plone.app.widgets 2.0.7
- site served over https

Here are a few examples:
![users edit](https://cloud.githubusercontent.com/assets/460742/22077855/251a64d2-dd73-11e6-95a2-ca7dc28b662c.png)
![users](https://cloud.githubusercontent.com/assets/460742/22077856/251fe7d6-dd73-11e6-8c35-4a31cd66dbb0.png)
![theming](https://cloud.githubusercontent.com/assets/460742/22077857/2521f5bc-dd73-11e6-82de-20736ca45b02.png)

**Comment by jensens** [comment]
Seems this is still an issue in coredev 5.1. I just prepared a preview page of my project with https and all is marked.
