### ISSUE TITLE
pat-querystring: Title gets ::-1 appended

### ISSUE THREAD

**Issue by jensens** [plone/mockup#716]
We found a bug when a `pat-querystring` plus a Title search is used like so:

![screenshot from 2016-10-05 14 20 27](https://cloud.githubusercontent.com/assets/157140/19112831/44b3ffd8-8b07-11e6-955c-62c4a03e9340.png)

Then in the generated querystring in javascript (the one send to the server on save, not the preview) the title gets a ::-1 appended:

![screenshot from 2016-10-05 14 21 43](https://cloud.githubusercontent.com/assets/157140/19112862/7577f43a-8b07-11e6-9579-334e6b7304b7.png)

Which results in a query with zero results.

In an subsequent edit the title contains the `::-1`:

![screenshot from 2016-10-05 14 27 02](https://cloud.githubusercontent.com/assets/157140/19112950/cf758182-8b07-11e6-8fc4-af617fb09b32.png)

**Comment by jensens** [comment]
kudos for finding this found are going to @chrimba

**Comment by tomgross** [comment]
The same (or at least a similar) issue occurs in the fulltext search of folder contents:

There is a `::1` appendend to the query where it should not. Here is an example `query` parameter of the `@@getVocabulary` view:
```
{"criteria":[{"i":"SearchableText","o":"plone.app.querystring.operation.string.contains","v":"bei*"},{"i":"path","o":"plone.app.querystring.operation.string.path","v":"/de/sandkasten::1"}],"sort_on":"getObjPositionInParent","sort_order":"ascending"}
```

**Comment by tomgross** [comment]
... And the issue is present in the related widget too

Here is an example of the `query` parameter of `@@getSource` view:
{"criteria":[{"i":"path","o":"plone.app.querystring.operation.string.path","v":"/Plone/de/sandkasten/foo/eduproduct-1-1::1"}],"sort_on":"path","sort_order":"ascending"}

**Comment by tomgross** [comment]
@thet can you please look into this.

**Comment by thet** [comment]
thats my next task.

**Comment by agitator** [comment]
works now with the merge of https://github.com/plone/plone.app.querystring/pull/83
