### ISSUE TITLE
TinyMCE - Image upload failed if "Upload to..." 

### ISSUE THREAD

**Issue by Gomez** [plone/mockup#718]
### Steps to reproduce
1. Create a folder (and change into it)
2. Add a Page
   3 In TinyMCE "Insert Image"
3. Click "Upload"
4. Browser to a local image
5. "Upload to..." is prefilled with the folder created before. 
6. Transfer failed.

It works if you remove the "Upload to" destination.

Tested with Plone 5.0.6

**Comment by pbauer** [comment]
This seems to be fixed with 5.0.7.

**Comment by pbauer** [comment]
I tried backporting the fix to a 5.0.6-project but checkouts of mockup and plone.app.content did not to the trick. Does anyone have a idea what actually fixed that?

**Comment by thet** [comment]
checking out plone.app.widgets?
compiling the bundles or using the resource registry in development mode and setting "develop javascript" on plone and plone-logged-in bundles?

**Comment by pbauer** [comment]
Found it \o/

It's a bug in plone.rest (https://github.com/plone/plone.rest/issues/50). My project depends on collective.solr which uses plone.restapi. plone.restapi registers services for `POST` using the `plone:service`-directive. As soon as any such service is registered the upload will fail: 

```
  <plone:service
      method="POST"
      name="@foo"
      for="Products.CMFCore.interfaces.ISiteRoot"
      factory=".foo.Bar"
      permission="cmf.ManagePortal"
      />
```

The traverser of plone.rest handles the POST-request and the ``fileUpload`` of `plone.app.content` method is never used. For more detail in th original issue.
I can fix it in my project by using a source-checkout of the branch with includes the fix. Thanks @buchi for fixing it. 
The fix will be included in plone.rest 1.0b1
