### ISSUE TITLE
pat-toggle broken in Plone

### ISSUE THREAD

**Issue by jensens** [plone/mockup#743]
I copied over the example at https://plone.github.io/mockup/dev/#pattern/toggle into a template in Plone (1:1) and it just does not do anything nor does it look like proposed.
So both, pattern and example are broken.

**Comment by vangheem** [comment]
Not every pattern in mockup is in plone by default. See https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/plone.js

The toggle pattern is not loaded.

**Comment by jensens** [comment]
a) we may need to document this?
b) there is the same pattern in patternslib - plone.patternslib does not use both b/c of conflicts. Should we get rif of pat-toggle in mockup and use/enhance the one in patternlsib?

cc @thet @pilz : what do you think?

**Comment by vangheem** [comment]
Yes, we should get rid of mockup's in favor of patternslib. We made a decision a while ago to make sure patternslib has all the general-use ones. mockup is now only for plone-specific patterns that do not belong anywhere else.

**Comment by djowett** [comment]
So it seems we should use bootstrap-collapse instead? But there is no collapse CSS.  This is confusing!

**Comment by Gomez** [comment]
Looks like mockup toggle will be replaced by patternlib toggle. Here are some notes: https://github.com/plone/mockup/pull/1034/
