### ISSUE TITLE
include link to http://plone.github.io/mockup/ in docs.plone.org

### ISSUE THREAD

**Issue by tkimnguyen** [plone/mockup#747]
We should include http://plone.github.io/mockup/ in docs.plone.org, as discussed in https://community.plone.org/t/plone5-change-friendly-datetime-format-in-folder-contents/3591/7

**Comment by janga1997** [comment]
@tkimnguyen I am not really where to add that in plone/documentation . I did not see a reply to your [query](https://community.plone.org/t/plone5-change-friendly-datetime-format-in-folder-contents/3591/2?u=janga1997) on that thread.

**Comment by tkimnguyen** [comment]
@janga1997 that's ok. Eventually someone will get around to it. @svx may have thoughts on it.

**Comment by gforcada** [comment]
@stevepiercy @thet @petschki I guess this can be closed already

**Comment by stevepiercy** [comment]
@gforcada no, where are the links between the two sites? There is no integration.

See also:

- https://github.com/plone/documentation/issues/1270
- https://github.com/plone/documentation/pull/1253

**Comment by gforcada** [comment]
Well, yes, sorry, I was short on words... I meant, that given that on the documentation repository there is already a tracking issue, and even a PR for it, we can close this one already.

**Comment by stevepiercy** [comment]
Technically you are correct, but it makes no sense to have a one-way "integration". This repository needs a link back to https://6.docs.plone.org/ or we need to decide how to better integrate the mockup docs and demo, similar to that which we did for the [Volto Storybook](https://6.docs.plone.org/storybook/). I'll create a new issue in this repo from this comment to clarify what should be done.
