### ISSUE TITLE
Just fixed a pattern, should I do something else ?

### ISSUE THREAD

**Issue by cedricmessiant** [plone/mockup#753]
I just fixed i18n in the upload pattern ( https://github.com/plone/mockup/commit/fdef6381c49d84be1966d649eab39bd65771e3e0 ) and updated `widgets.pot` in `plone.app.locales` ( https://github.com/collective/plone.app.locales/commit/2a8df1b1a50f141577c078c91074744badb9d64b ). I wonder if I have to do something else to ensure that the new javascript will be used in next Plone release ? (I had to rebuild `plone-logged-in` bundle to see the change in my Plone site)

**Comment by thet** [comment]
That should be fine. The stepts to include it in the next Plone release would be

- build plone-logged-in for CMFPlone,
- update the last compile time of the plone-logged-in bundle in CMFPlone / profiles / dependencies / registry.xml
- also make sure, that plone.app.upgrade updates the last-compile-time.

but that should be done anyways before the next release of Plone 5.1

**Comment by cedricmessiant** [comment]
Ok, thanks !
