### ISSUE TITLE
TinyMCE missing translations

### ISSUE THREAD

**Issue by yleclanche** [plone/mockup#760]
There are missing translations in TinyMCE, in French but probably in other languages too.

The Increase indent show _en.Increase Indent_ on the demo page : http://plone.github.io/mockup/dev/#pattern/tinymce
And show _fr_FR.Increase indent_ in french.

Table buttons have the same issue (in english too).

Those translations are presents in the js file so it's not just a missing line in a file.

Insert link and insert image popups have lots of missing translations too.

**Comment by petschki** [comment]
See #849
