### ISSUE TITLE
the warning message shown when filtering contents doesn't go away when removing all the filters

### ISSUE THREAD

**Issue by arsenico13** [plone/mockup#812]
If you are in Contents view and try to apply a filter, a warning message appears, saying:
_"Can not order items while querying"_

Aside the fact that this message is misleading
(as I explained here https://github.com/collective/plone.app.locales/issues/173), 
**that message never goes away, even if you remove all the filters**.
You have to reload the entire page to make it disappear.

**Comment by thet** [comment]
Duplicate of: https://github.com/plone/mockup/issues/672
