### ISSUE TITLE
TinyMCE's content.min.css included in bundle css

### ISSUE THREAD

**Issue by petschki** [plone/mockup#838]
Is it really necessary to include TinyMCE's ``content.min.css`` in the ``pattern.tinymce.less`` file? 

https://github.com/plone/mockup/blob/acb88e4baa20a2e70bb798f5f9eb4bf7ef891bb0/mockup/patterns/tinymce/less/pattern.tinymce.less#L2

From my understanding this file is loaded async with the ``tinyOptions.content_css`` which can be configured in the pattern options for individual content css classes but please correct me if I'm wrong.

https://github.com/plone/mockup/blob/acb88e4baa20a2e70bb798f5f9eb4bf7ef891bb0/mockup/patterns/tinymce/pattern.js#L181

If it should be bundled, then my next question is, why the extra copy/sed grunt tasks only for this file?

https://github.com/plone/mockup/blob/acb88e4baa20a2e70bb798f5f9eb4bf7ef891bb0/mockup/js/grunt.js#L97-L98
https://github.com/plone/mockup/blob/acb88e4baa20a2e70bb798f5f9eb4bf7ef891bb0/mockup/js/grunt.js#L152-L179

**Comment by pnicolli** [comment]
In addition, if this is an intended change, it should probably be marked as a breaking change, because it applies styles (font-family and other sizing things) to the body element.
Imho it doesn't look like what we want here, though.

**Comment by frapell** [comment]
@petschki Thanks for pointing this out, it was indeed a bug.

I have solved it in https://github.com/plone/mockup/pull/854, once build is green, it can be merged.

For fixing https://github.com/plone/Products.CMFPlone/issues/2430 we will need to recompile mockup for each branch were this was included, I believe 5.0, 5.1 and 5.2
