### ISSUE TITLE
Include column sorting for the structure pattern

### ISSUE THREAD

**Issue by frapell** [plone/mockup#848]
We used to have this feature in Plone, where you could sort the elements inside the table for the folder_contents view, without affecting the actual order of items inside the folder.

You can rearrange items in the folder_contents, but that affects the actual order of items.

I am thinking on integrating a solution in order to provide this feature back, and I came across 2 alternatives:

https://datatables.net/ and http://issues.wenzhixin.net.cn/bootstrap-table/

I already integrated datatables in a project, so I know it works well with Mockup, but I don't know if it is something that it would be accepted to be included with the project.

What do you guys think?

**Comment by frapell** [comment]
@vangheem @thet What do you guys think?

**Comment by thet** [comment]
Sounds good to me + I'm not against it.

AFAIK Datatables brings a lot of table rendering functionality including search, which would make parts of structure patterns code obsolete. I'm not sure if it's easy to integrate.

Before it's going to be a major rewrite I'd put efforts to a React based rewrite of the structure pattern (plone-react). My plan is to look into a React option at the Buschenschanksprint ( https://community.plone.org/t/buschenschanksprint-2018-11-6-15-6-2018/6154 ) including an alternative to the Related Items Widget (a frequent source of complaints from my customers).

/cc @tisto any opinions?

**Comment by thet** [comment]
Absolutely. Go for it :)
