### ISSUE TITLE
travis IE test running on linux and phantomjs?

### ISSUE THREAD

**Issue by sunew** [plone/mockup#872]
This is the IE_9 job in travis:

![selection_663](https://user-images.githubusercontent.com/893142/45782485-6bbaf980-bc63-11e8-85a7-417fa27575c6.png)

**Comment by sunew** [comment]
My point is something is wrong with the setup.... The IE9 job does not really seem to be an IE9 job

**Comment by vincentfretin** [comment]
Actually all browsers 
  matrix:                                                                       
    - BROWSERS="SL_Chrome"                                                      
    - BROWSERS="SL_Firefox"                                                     
    - BROWSERS="SL_IE_9"                                                        
    - BROWSERS="SL_IE_10,SL_IE_11"                                              
    - BROWSERS="SL_Opera,SL_Safari"                                             
    - BROWSERS="SL_IPhone"                                                      
    - BROWSERS="SL_IPad"                                                        
    - BROWSERS="SL_Android" 
seems to use phantomjs instead of SauceLabs?

**Comment by vincentfretin** [comment]
@tisto you may have a better idea, maybe there is is a configuration issue with travis/SauceLabs/karma ? This is an area where I have zero knowledge.

**Comment by tisto** [comment]
@tisto I have no clue about the mockup test setup and we completely moved forward to Cypress/jest/etc. PhantomJS is dead since chrome and firefox became headless. Testing IE9 in 2020 is nuts IMHO. Sorry, I am not able to help much here I guess.

**Comment by vincentfretin** [comment]
Thanks for the reply. Yeah I know phantomjs is dead. mockup can launch the tests with Chrome as well with `make test-dev`. We should probably use only that in travis and ditch phantomjs and saucelabs. There is one test that is failing with chrome though.

**Comment by vincentfretin** [comment]
If fixed the failing test in chrome https://github.com/plone/mockup/commit/c93a84e6cacbc64b0d93c428d7e997efafad050b

This was the test for the toolbar pattern that was moved to mockup "recently".

**Comment by vincentfretin** [comment]
related comment https://github.com/plone/mockup/issues/865#issuecomment-421550363

**Comment by gforcada** [comment]
travis is long not a solution, is this still relevant? 🤔
