### ISSUE TITLE
Mockup eventedit does not update end-date on latest Plone 5.1.4

### ISSUE THREAD

**Issue by Netroxen** [plone/mockup#880]
Story
-------

As a user
I want to be able to select a start date and have the end date automatically update
so that I do not need to select the same date again.

Versions
------------

Plone 5.1.4 (5114)
CMF 2.2.12
Zope 2.13.27
Python 2.7.14 (default, Oct 9 2017, 22:27:46) [GCC 4.8.4]
PIL 5.2.0 (Pillow)

[Tested when adding an Event on demo.plone.org](http://demo.plone.org/en/++add++Event).
[The responsible mockup method?](https://github.com/plone/mockup/blob/master/mockup/patterns/eventedit/pattern.js#L188)

Expected Result
----------------------

When I add an Event item on a default Plone site, and I open and select a start date with the datepicker, the end date should also be updated with my selection.

Current Result
--------------------

When I add an Event item on a default Plone site, and I open and select a start date with the datepicker, the end date is not updated and I must again, select the same date.

Additional Information
-----------------------------

This was tested on the latest Plone version, although this seems to be broken in most (if not all) Plone 5.1.x releases.

**Comment by pbauer** [comment]
I tested it in coredev and vanilla 5.1.4 and it works. It is broken ob demo.plone.org though and that needs to be investigated.
