### ISSUE TITLE
Fix alignment of the default page element in the structure pattern

### ISSUE THREAD

**Issue by ale-rt** [plone/mockup#895]
The :before pseudo element breaks the alignment of the icons and titles, see:
![image](https://user-images.githubusercontent.com/1300763/53285676-9f92d180-3763-11e9-9505-89f8b15e3c89.png)

**Comment by fulv** [comment]
I think you meant to use `position: absolute;` instead of `fixed`.
For a humorous effect, try scrolling up and down.
