### ISSUE TITLE
Upgrade to jQuery 3

### ISSUE THREAD

**Issue by fulv** [plone/mockup#917]
I'm opening this ticket to start planning for an upgrade to jQuery 3, possibly targeting a Plone 6 release.

The upgrade itself could be fairly straightforward by using jquery-migrate.  The tricky part is identifying and testing all the most important add-ons that contain JS code relying on jQuery, as well as upgrading all the dependencies if we want to have as close to zero npm security vulnerabilities as possible (at least at launch time).

How you can help:  edit this ticket and add to the following list of Plone addons that need to be tested with jQuery 3.

* collective.isotope
* eea.facetednavigation
*

**Comment by fulv** [comment]
Does this need a PLIP?

**Comment by vincentfretin** [comment]
see https://github.com/plone/mockup/pull/989

**Comment by MrTango** [comment]
I my opinion it does not need a PLIP for upgrading it.
In Plone core one problem is the drag&drop lib which does not work with newer JQ, this need to be solved.

**Comment by MrTango** [comment]
this is the error with the drag&drop lib we have too: https://github.com/threedubmedia/jquery.threedubmedia/pull/6

**Comment by thet** [comment]
See: https://github.com/plone/plone.staticresources/issues/71
