### ISSUE TITLE
Tinymce pattern: Link popup looses tab selection on active link type

### ISSUE THREAD

**Issue by parruc** [plone/mockup#921]
When I insert an external link in tiny selecting some text and clicking the link button, the resulting popup has several tabs including internal, upload, external ecc.

When I inserted one or more links, save the content and edit it back, when I try to change the link the selected tab is not the one where I entered the data before but it's always "internal". That's bad cause I have to click on all tabs to find what kind of link it was.

**Comment by mamico** [comment]
#922 merged
