### ISSUE TITLE
Querystring pattern fails to handle UIDs prior to 2011 (plone.uuid < 1.0.2)

### ISSUE THREAD

**Issue by laulaz** [plone/mockup#939]
Before `plone.uuid` 1.0.2 : there were dashes in UIDs.
After : dashes were removed in UIDs.

The querystring path widget does not handle old UIDs correctly, because of this regexp (and maybe other code elsewhere) :
https://github.com/plone/mockup/blob/ab1d2063de8fbec46378f566f68713756e9ca96f/mockup/patterns/querystring/pattern.js#L262

See the difference between a "new" UID and an (very) old UID in collection criteria :
<img width="701" alt="query" src="https://user-images.githubusercontent.com/1101273/73837115-1019ed80-4811-11ea-85d0-e0ba3a28eedc.png">

**Comment by laulaz** [comment]
- Old way to generate UIDs: `str(uuid.uuid4())`, ex : `42835931-9dc4-47cc-94ae-b248082b07eb` (--> 4 dashes, 36 characters in total)
- New way to generate UIDs: `uuid.uuid4().hex`, ex : `b577a22aa96d4d36b5f16fb32ca201b2` (--> 0 dashes, 32 characters in total)

To make things simple, I would propose to change regexp from `^[0-9a-f]{32}::-?[0-9]+$` to `^[0-9a-f\-]{32,36}::-?[0-9]+$`.

**Comment by thet** [comment]
Fixed by: https://github.com/plone/mockup/pull/940
