### ISSUE TITLE
In the TinyMCE-pattern, linkTypes can be used to control the tabs in the image modal, but not in the link modal

### ISSUE THREAD

**Issue by batlock666** [plone/mockup#946]
When customizing the TinyMCE-pattern, the option linkTypes can be used to control which tabs are shown in the image modal. However, this does not work in the link modal, even though they use the same code. The reason for this is the template link.xml, which does not have tests for the tabs, while the template image.xml does have the tabs.

I believe that template link.xml should also have the tests for the tabs.

**Comment by thet** [comment]
Closed via: https://github.com/plone/mockup/pull/947
