### ISSUE TITLE
Structure pattern: action buttons should only be present if there is some action to do

### ISSUE THREAD

**Issue by erral** [plone/mockup#961]
As part or an accessibility review we were requested to hide all actions present in the folder contents view (copy, paste, cut, rearrange, change properties, workflow, ...) if there is no items selected. Morever, the paste action should only be visible is there is something to paste.

@ionlizarazu

**Comment by vincentfretin** [comment]
This was a regression. See my fixes in https://github.com/plone/mockup/pull/996
