### ISSUE TITLE
Plone 5.1.x does not have image caption enabled on TinyMCE

### ISSUE THREAD

**Issue by tuticapi** [plone/mockup#977]
TinyMCE: Add support for image captions.
In a short time a pull request will be sent to enable it

ref:
https://github.com/plone/plone.app.upgrade/issues/231
https://github.com/plone/plone.outputfilters/issues/37
https://github.com/plone/Products.CMFPlone/issues/3098

**Comment by vincentfretin** [comment]
Image caption feature is available in Plone 5.2.2.
