### ISSUE TITLE
make docs fails on MacOS

### ISSUE THREAD

**Issue by petri** [plone/mockup#980]
Followed instructions in the GETTING STARTED doc. After running `make bootstrap` successfully, `make docs` fails. It's as if a needed `react.js` file is missing:

```
petri@PetriMac mockup % make docs
rm -Rf mockup/docs; mkdir mockup/docs; cp -R .git mockup/docs; cd mockup/docs; git checkout gh-pages;
Checking out files: 100% (5301/5301), done.
Switched to branch 'gh-pages'
Your branch is up to date with 'origin/gh-pages'.
# if test ! -d mockup/docs; then git clone git://github.com/plone/mockup.git -b gh-pages mockup/docs; fi
rm -rf mockup/docs/dev
NODE_PATH=./mockup/node_modules ./mockup/node_modules/grunt-cli/bin/grunt bundle-docs   --gruntfile=mockup/Gruntfile.js
Running "requirejs:docs" (requirejs) task
>> Error: ENOENT: no such file or directory, open
>> '/Users/petri/Code/mockup/mockup/react.js'
>> In module tree:
>>     mockup-bundles-docs
>>       mockup-docs
Warning: RequireJS failed. Use --force to continue.

Aborted due to warnings.
make: *** [docs] Error 6
```

**Comment by ale-rt** [comment]
+1 it fails also on focal fossa.
I restarted the build for master and it is broken as well: https://travis-ci.org/github/plone/mockup/branches
@thet any idea?

**Comment by vincentfretin** [comment]
FYI I fixed the tests on master with https://github.com/plone/mockup/commit/ee295587a1386eafe42be7bc600a8299919dae62

**Comment by vincentfretin** [comment]
I have the same error on my machine with Ubuntu 18.04. This doesn't seem to be OS releated anyway.
The grunt task wants `mockup/react.js` and it's not there...
