### ISSUE TITLE
inlinevalidation broken for select fields

### ISSUE THREAD

**Issue by abosio** [plone/mockup#981]
This [change to use a cloned form](https://github.com/plone/mockup/commit/e583f013e28028b1f9edc58f919da067b1136185) for the validation submission causes problems validating select fields because clone does not copy user selections made to them.

This is [noted in the jQuery documentation](https://api.jquery.com/clone/#clone-withDataAndEvents) and mentions it that also affects textarea, though I have not tested textarea validation in Plone.

My bug and investigation is using Plone 5.2.1.

To reproduce:
- create a content type in dexterity control panel
- add a Choice field
- add some options to the field
- add an instance of your new content object in Plone somewhere
- open your browsers web inspector and view the xhr requests in the Network tab
- select any option except the first one and then tab or click on any other field to "blur" the field
- click on the new xhr request that appeared in the Network tab of the web inspector
- view the request body for it and you will see the value that was posted for validation was not the one you selected but whatever value is first in the list

For us this is causing a problem with a filesystem developed content type where we have a custom validator, but in any case sending the wrong value is a problem.

**Comment by frapell** [comment]
@abosio Thanks for the report, this has already been fixed in https://github.com/plone/mockup/issues/971 it should be included in the next release of mockup.

**Comment by abosio** [comment]
Ah, thanks. Sorry that didn't turn up in my search before submitting.
